parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  ecmaFeatures:
    jsx: true
extends:
  - 'plugin:@typescript-eslint/recommended'
  - plugin:react/recommended
  - plugin:prettier/recommended
rules:
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-unused-vars':
    - error
    - args: after-used
      ignoreRestSiblings: true
      argsIgnorePattern: '^_'
  react/display-name: off
  react/prop-types: off
  '@typescript-eslint/no-empty-function': off
  '@typescript-eslint/ban-types': off
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/no-extra-semi': off
settings:
  react:
    version: detect
