# parser: ./lib/index.js
plugins:
  - coffee
  - known-imports
  - prettier
  - react
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:coffee/all
  - plugin:coffee/prettier
  - plugin:known-imports/recommended-react
rules:
  coffee/prefer-destructuring: [error, {object: true}]
  coffee/no-unused-vars: off
  known-imports/no-unused-vars: [error, {varsIgnorePattern: ^_+$}]
  require-jsdoc: error
  prefer-rest-params: error
  # no-else-return: error
  # id-length: error
  # no-multi-assign: error
  no-self-compare: error
  coffee/no-magic-numbers: off
  coffee/no-implicit-coercion: off
  coffee/vars-on-top: off
  coffee/max-depth: off
  coffee/complexity: off
  coffee/max-lines-per-function: off
  coffee/capitalized-comments: off
  coffee/spaced-comment: off
  coffee/no-underscore-dangle: off
  coffee/no-commonjs: off
  coffee/valid-jsdoc: off
  coffee/multiline-comment-style: off
  coffee/no-return-assign: off
  # coffee/no-overwrite: [error, sameScope: false]
  coffee/block-scoped-var: off
  coffee/wrap-regex: off
  coffee/no-default-export: off
  coffee/jsx-no-bind: off
  coffee/no-anonymous-default-export: off
  coffee/guard-for-in: off
  no-sparse-arrays: off
env:
  node: true
  es6: true
  jest: true
