plugins:
  - coffee
  - known-imports
  - prettier
extends:
  - eslint:recommended
  - plugin:coffee/all
  - plugin:coffee/react-recommended
  - plugin:coffee/prettier-run-as-rule
  - plugin:known-imports/recommended-react
  - plugin:coffee/import-all
rules:
  coffee/prefer-destructuring: [error, {object: true}]
  coffee/no-unused-vars: off
  known-imports/no-unused-vars: [error, {varsIgnorePattern: ^_+$}]
  prefer-rest-params: error
  # no-else-return: error
  # id-length: error
  # no-multi-assign: error
  no-self-compare: error
  coffee/no-magic-numbers: off
  coffee/no-implicit-coercion: off
  coffee/vars-on-top: off
  coffee/max-depth: off
  coffee/complexity: off
  coffee/max-lines-per-function: off
  coffee/capitalized-comments: off
  coffee/spaced-comment: off
  coffee/no-underscore-dangle: off
  coffee/no-commonjs: off
  coffee/valid-jsdoc: off
  coffee/multiline-comment-style: off
  coffee/no-return-assign: off
  coffee/no-cond-assign: off
  # coffee/no-overwrite: [error, sameScope: false]
  coffee/block-scoped-var: off
  coffee/wrap-regex: off
  coffee/no-default-export: off
  coffee/jsx-no-bind: off
  coffee/no-anonymous-default-export: off
  coffee/guard-for-in: off
  no-sparse-arrays: off
  coffee/no-invalid-this: off
  require-jsdoc: off
  coffee/require-jsdoc: off
  coffee/display-name: off
  coffee/no-empty-function: off
  sort-imports: off
  callback-return: off
  coffee/id-length: off
  max-statements: off
  default-case: off
  no-inline-comments: off
  no-plusplus: off
  no-warning-comments: off
  sort-keys: off
  require-unicode-regexp: off
  coffee/callback-return: off
  import/group-exports: off
  coffee/no-named-export: off
  import/no-internal-modules: off
  import/max-dependencies: off
  import/no-relative-parent-imports: off
  import/no-unassigned-import: off
  import/order: [error, {newlines-between: always}]
env:
  node: true
  es6: true
  jest: true
  browser: true
