"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports["default"] = _default;

var _addWrapper = _interopRequireDefault(require("./addWrapper"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { "default": obj }; }

// Generated by CoffeeScript 2.5.0
function _default() {
  return (0, _addWrapper["default"])(function (_ref) {
    var render = _ref.render;
    return render();
  });
}

;