"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports["default"] = _default;
exports.isAddDisplayName = void 0;
// Generated by CoffeeScript 2.5.0
var markerPropertyName;
markerPropertyName = '__ad-hok-addDisplayName'; // eslint-disable-next-line known-imports/no-unused-vars

var isAddDisplayName = function isAddDisplayName(func) {
  return func[markerPropertyName];
};

exports.isAddDisplayName = isAddDisplayName;

function _default(displayName) {
  var ret;

  ret = function ret(props) {
    return props;
  };

  ret[markerPropertyName] = [displayName];
  return ret;
}

;