"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports["default"] = _default;
exports.isAddPropTypes = void 0;

var _react = _interopRequireDefault(require("react"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { "default": obj }; }

// Generated by CoffeeScript 2.5.0
var markerPropertyName;
markerPropertyName = '__ad-hok-addPropTypes'; // eslint-disable-next-line known-imports/no-unused-vars

var isAddPropTypes = function isAddPropTypes(func) {
  return func[markerPropertyName];
};

exports.isAddPropTypes = isAddPropTypes;

function _default(propTypes) {
  var ret;

  ret = function ret(Component) {
    Component.propTypes = propTypes;
    return function (props) {
      return _react["default"].createElement(Component, props);
    };
  };

  ret[markerPropertyName] = true;
  return ret;
}

;