"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports["default"] = void 0;

var _helpers = require("./util/helpers");

var _useComputedFromDependencies = _interopRequireDefault(require("./util/useComputedFromDependencies"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { "default": obj }; }

function ownKeys(object, enumerableOnly) { var keys = Object.keys(object); if (Object.getOwnPropertySymbols) { var symbols = Object.getOwnPropertySymbols(object); if (enumerableOnly) symbols = symbols.filter(function (sym) { return Object.getOwnPropertyDescriptor(object, sym).enumerable; }); keys.push.apply(keys, symbols); } return keys; }

function _objectSpread(target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i] != null ? arguments[i] : {}; if (i % 2) { ownKeys(Object(source), true).forEach(function (key) { _defineProperty(target, key, source[key]); }); } else if (Object.getOwnPropertyDescriptors) { Object.defineProperties(target, Object.getOwnPropertyDescriptors(source)); } else { ownKeys(Object(source)).forEach(function (key) { Object.defineProperty(target, key, Object.getOwnPropertyDescriptor(source, key)); }); } } return target; }

function _defineProperty(obj, key, value) { if (key in obj) { Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true }); } else { obj[key] = value; } return obj; }

// Generated by CoffeeScript 2.5.0
var addProps;

addProps = function addProps(updater, dependencies) {
  return function (props) {
    var addedProps, getAddedProps;

    getAddedProps = function getAddedProps() {
      if ((0, _helpers.isFunction)(updater)) {
        return updater(props);
      } else {
        return updater;
      }
    };

    addedProps = (0, _useComputedFromDependencies["default"])({
      compute: getAddedProps,
      dependencies: dependencies,
      props: props
    });
    return _objectSpread({}, props, {}, addedProps);
  };
};

var _default = addProps;
exports["default"] = _default;