"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports["default"] = _default;

// Generated by CoffeeScript 2.5.0
function _default(test, consequent) {
  var alternate = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : function (props) {
    return props;
  };
  return function (props) {
    if (test(props)) {
      return consequent(props);
    } else {
      return alternate(props);
    }
  };
}

;