"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports["default"] = _default;

var _react = _interopRequireDefault(require("react"));

var _flowMax = _interopRequireDefault(require("./flowMax"));

var _branchAvoidCircularDependency = require("./branch-avoid-circular-dependency");

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { "default": obj }; }

// Generated by CoffeeScript 2.5.0
function _default(test, consequent) {
  var alternate = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : function (props) {
    return props;
  };
  var ret;

  ret = function ret(Component) {
    var AlternateAsComponent, ConsequentAsComponent, createAlternate, createConsequent;
    ConsequentAsComponent = null;

    createConsequent = function createConsequent() {
      var Consequent, ref;
      Consequent = (0, _flowMax["default"])(consequent, Component);

      if (Consequent.displayName == null || Consequent.displayName === 'ret') {
        Consequent.displayName = "branch(".concat((ref = Component.displayName) != null ? ref : '', ")");
      }

      return Consequent;
    };

    AlternateAsComponent = null;

    createAlternate = function createAlternate() {
      var Alternate, ref;
      Alternate = (0, _flowMax["default"])(alternate, Component);

      if (Alternate.displayName == null || Alternate.displayName === 'ret') {
        Alternate.displayName = "branch(".concat((ref = Component.displayName) != null ? ref : '', ")");
      }

      return Alternate;
    };

    return function (props) {
      if (test(props)) {
        if (ConsequentAsComponent == null) {
          ConsequentAsComponent = createConsequent();
        }

        return _react["default"].createElement(ConsequentAsComponent, props);
      } else {
        if (AlternateAsComponent == null) {
          AlternateAsComponent = createAlternate();
        }

        return _react["default"].createElement(AlternateAsComponent, props);
      }
    };
  };

  ret[_branchAvoidCircularDependency.markerPropertyName] = true;
  return ret;
}

;