"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.addReducer = exports.addMemoBoundary = exports.addDefaultProps = exports.addDisplayName = exports.addWrapperHOC = exports.addWrapper = exports.returns = exports.branchPure = exports.branch = exports.renderNothing = exports.flowMax = exports.addContext = exports.addPropTypes = exports.addHandlers = exports.addRef = exports.addProps = exports.addLayoutEffect = exports.addEffect = exports.addStateHandlers = exports.addState = void 0;
var addState_1 = require("./addState");
Object.defineProperty(exports, "addState", { enumerable: true, get: function () { return __importDefault(addState_1).default; } });
var addStateHandlers_1 = require("./addStateHandlers");
Object.defineProperty(exports, "addStateHandlers", { enumerable: true, get: function () { return __importDefault(addStateHandlers_1).default; } });
var addEffect_1 = require("./addEffect");
Object.defineProperty(exports, "addEffect", { enumerable: true, get: function () { return __importDefault(addEffect_1).default; } });
var addLayoutEffect_1 = require("./addLayoutEffect");
Object.defineProperty(exports, "addLayoutEffect", { enumerable: true, get: function () { return __importDefault(addLayoutEffect_1).default; } });
var addProps_1 = require("./addProps");
Object.defineProperty(exports, "addProps", { enumerable: true, get: function () { return __importDefault(addProps_1).default; } });
var addRef_1 = require("./addRef");
Object.defineProperty(exports, "addRef", { enumerable: true, get: function () { return __importDefault(addRef_1).default; } });
var addHandlers_1 = require("./addHandlers");
Object.defineProperty(exports, "addHandlers", { enumerable: true, get: function () { return __importDefault(addHandlers_1).default; } });
var addPropTypes_1 = require("./addPropTypes");
Object.defineProperty(exports, "addPropTypes", { enumerable: true, get: function () { return __importDefault(addPropTypes_1).default; } });
var addContext_1 = require("./addContext");
Object.defineProperty(exports, "addContext", { enumerable: true, get: function () { return __importDefault(addContext_1).default; } });
var flowMax_1 = require("./flowMax");
Object.defineProperty(exports, "flowMax", { enumerable: true, get: function () { return __importDefault(flowMax_1).default; } });
var renderNothing_1 = require("./renderNothing");
Object.defineProperty(exports, "renderNothing", { enumerable: true, get: function () { return __importDefault(renderNothing_1).default; } });
var branch_1 = require("./branch");
Object.defineProperty(exports, "branch", { enumerable: true, get: function () { return __importDefault(branch_1).default; } });
var branchPure_1 = require("./branchPure");
Object.defineProperty(exports, "branchPure", { enumerable: true, get: function () { return __importDefault(branchPure_1).default; } });
var returns_1 = require("./returns");
Object.defineProperty(exports, "returns", { enumerable: true, get: function () { return __importDefault(returns_1).default; } });
var addWrapper_1 = require("./addWrapper");
Object.defineProperty(exports, "addWrapper", { enumerable: true, get: function () { return __importDefault(addWrapper_1).default; } });
var addWrapperHOC_1 = require("./addWrapperHOC");
Object.defineProperty(exports, "addWrapperHOC", { enumerable: true, get: function () { return __importDefault(addWrapperHOC_1).default; } });
var addDisplayName_1 = require("./addDisplayName");
Object.defineProperty(exports, "addDisplayName", { enumerable: true, get: function () { return __importDefault(addDisplayName_1).default; } });
var addDefaultProps_1 = require("./addDefaultProps");
Object.defineProperty(exports, "addDefaultProps", { enumerable: true, get: function () { return __importDefault(addDefaultProps_1).default; } });
var addMemoBoundary_1 = require("./addMemoBoundary");
Object.defineProperty(exports, "addMemoBoundary", { enumerable: true, get: function () { return __importDefault(addMemoBoundary_1).default; } });
var addReducer_1 = require("./addReducer");
Object.defineProperty(exports, "addReducer", { enumerable: true, get: function () { return __importDefault(addReducer_1).default; } });
