"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports["default"] = void 0;

var _react = require("react");

// Generated by CoffeeScript 2.5.0
var usePrevious;

usePrevious = function usePrevious(val) {
  var ref;
  ref = (0, _react.useRef)();
  (0, _react.useEffect)(function () {
    ref.current = val;
    return void 0;
  });
  return ref.current;
};

var _default = usePrevious;
exports["default"] = _default;