"use strict";

var _react = _interopRequireDefault(require("react"));

var _reactTestingLibrary = require("react-testing-library");

require("jest-dom/extend-expect");

var _propTypes = _interopRequireDefault(require("prop-types"));

var _ = require("..");

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { "default": obj }; }

// Generated by CoffeeScript 2.5.0

/* eslint-disable no-console */
var Comp, Comp2;
Comp = (0, _.flowMax)((0, _.addPropTypes)({
  a: _propTypes["default"].number.isRequired
}), function (_ref) {
  var a = _ref.a;
  return _react["default"].createElement("div", null, _react["default"].createElement("div", {
    "data-testid": "a"
  }, a));
});
Comp2 = (0, _.flowMax)((0, _.addProps)({
  b: 3
}), (0, _.addPropTypes)({
  c: _propTypes["default"].number.isRequired
}), function (_ref2) {
  var c = _ref2.c;
  return _react["default"].createElement("div", null, _react["default"].createElement("div", {
    "data-testid": "c"
  }, c));
});
describe('addPropTypes', function () {
  beforeAll(function () {
    return jest.spyOn(console, 'error').mockImplementation(function () {});
  });
  afterAll(function () {
    return console.error.mockRestore();
  });
  afterEach(function () {
    return console.error.mockClear();
  });
  test('non-initial works', function () {
    (0, _reactTestingLibrary.render)(_react["default"].createElement(Comp2, {
      c: 3
    }));
    return expect(console.error).not.toHaveBeenCalled();
  });
  test('non-initial works with wrong prop types', function () {
    (0, _reactTestingLibrary.render)(_react["default"].createElement(Comp2, {
      c: true
    }));
    return expect(console.error).toHaveBeenCalled();
  });
  test('works', function () {
    (0, _reactTestingLibrary.render)(_react["default"].createElement(Comp, {
      a: 3
    }));
    return expect(console.error).not.toHaveBeenCalled();
  });
  return test('works with wrong prop types', function () {
    (0, _reactTestingLibrary.render)(_react["default"].createElement(Comp, {
      a: true
    }));
    return expect(console.error).toHaveBeenCalled();
  });
});