"use strict";

var _ = require("..");

// Generated by CoffeeScript 2.5.0
describe('returns', function () {
  test('works as initial step', function () {
    var ret;
    ret = (0, _.flowMax)((0, _.returns)(function (val) {
      return val + 2;
    }), function () {
      return 4;
    })(1);
    return expect(ret).toBe(3);
  });
  test('works as non-initial step', function () {
    var ret;
    ret = (0, _.flowMax)(function () {
      return 2;
    }, (0, _.returns)(function (val) {
      return val + 1;
    }), function () {
      return 4;
    })(1);
    return expect(ret).toBe(3);
  });
  return test('works with branchPure()', function () {
    var ret, returnThreeIfGreaterThanOne;
    returnThreeIfGreaterThanOne = (0, _.flowMax)((0, _.branchPure)(function (x) {
      return x > 1;
    }, (0, _.returns)(function (val) {
      return val + 1;
    })), function () {
      return 4;
    });
    ret = returnThreeIfGreaterThanOne(2);
    expect(ret).toBe(3);
    ret = returnThreeIfGreaterThanOne(1);
    return expect(ret).toBe(4);
  });
});