"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports["default"] = void 0;
// Generated by CoffeeScript 2.5.0
var _default = {
  get: jest.fn(function () {
    return Promise.resolve({
      data: {}
    });
  })
};
exports["default"] = _default;